'use strict';

const fs = require('fs');
const path = require('path');

// Fields holding credentials. They are encrypted at rest with Electron's
// safeStorage when the OS keyring is available.
const SECRET_PATHS = [
  ['openai', 'apiKey'],
  ['mail', 'password'],
];

const DEFAULT_SETTINGS = {
  openai: {
    apiKey: '',
    model: 'gpt-4.1-mini',
    baseURL: '',
  },
  // Outbound: customer emails are submitted to the scenario mail server.
  mail: {
    host: '',
    smtpPort: 25,
    smtpSecurity: 'starttls', // none | starttls | tls
    allowSelfSigned: true,
    smtpAuth: false,
    username: '',
    password: '',
  },
  // Inbound: the scenario mail server delivers replies for customer domains here.
  listener: {
    bindAddress: '0.0.0.0',
    port: 25,
    offerStartTls: true,
    extraAllowedIps: [], // besides the mail server's own address(es)
  },
  scenario: {
    customerTld: 'local', // fictional TLD for customer domains
    guidance: '', // extra instructions for the customer personas
    minIntervalMin: 20,
    maxIntervalMin: 90,
    replyDelayMinSec: 900,
    replyDelayMaxSec: 7200,
    workingHoursOnly: false,
    workStartHour: 8,
    workEndHour: 18,
    followUpEnabled: true,
    followUpMinHours: 4, // chase an unanswered email after this long…
    followUpMaxHours: 24, // …up to this long (scenario time)
    followUpMax: 2, // follow-ups per unanswered email
    partyFollowUps: false, // external parties chase their own unanswered questions
    pace: 1, // 1 = real business time; e.g. 60 = an hour passes in a minute
  },
};

const DEFAULT_DATA = {
  settings: DEFAULT_SETTINGS,
  // Defined entirely by the user.
  company: {
    name: '',
    domain: '',
    description: '',
    operatingYear: null, // e.g. 2005: the scenario runs as if it were that year
    datedEmails: true, // put the operating-year date in email Date headers
    employees: [], // { name, email, role, responsibilities }
  },
  // Virtual customers, generated by OpenAI and editable.
  customers: [], // { name, email, organisation, role, personality, writingStyle, signature }
  // External parties (suppliers, contractors, accountants...), defined by the user.
  // They only ever respond to emails; they never start conversations.
  parties: [], // { name, email, organisation, role, services, personality, writingStyle, signature }
  threads: {}, // threadId -> { id, subject, customer, messages: [] }
  msgIndex: {}, // Message-ID -> threadId
  sentIds: {}, // Message-IDs we generated
  processedIds: {}, // inbound Message-IDs already handled
  pending: [], // scheduled customer replies, survive restarts
  log: [], // activity log: { time, level, message }
  // App-level state, never written into .senario files.
  appState: { currentFile: null, includeSecrets: false, autoSave: true },
};

const MAX_LOG = 5000;

function deepMerge(base, over) {
  if (Array.isArray(base) || typeof base !== 'object' || base === null) {
    return over === undefined ? base : over;
  }
  const out = { ...base };
  for (const key of Object.keys(over || {})) {
    out[key] = key in base ? deepMerge(base[key], over[key]) : over[key];
  }
  return out;
}

class Store {
  constructor(dir, safeStorage) {
    this.file = path.join(dir, 'senario-data.json');
    this.safeStorage = safeStorage;
    this.data = this._load();
    this._timer = null;
  }

  _canEncrypt() {
    try {
      return !!this.safeStorage && this.safeStorage.isEncryptionAvailable();
    } catch {
      return false;
    }
  }

  _load() {
    let raw = {};
    try {
      raw = JSON.parse(fs.readFileSync(this.file, 'utf8'));
    } catch {
      // first run or unreadable file: start fresh
    }
    const data = deepMerge(DEFAULT_DATA, raw);
    for (const [a, b] of SECRET_PATHS) {
      const v = data.settings[a][b];
      if (typeof v === 'string' && v.startsWith('enc:')) {
        try {
          data.settings[a][b] = this.safeStorage.decryptString(Buffer.from(v.slice(4), 'base64'));
        } catch {
          data.settings[a][b] = '';
        }
      }
    }
    return data;
  }

  save() {
    if (this.onChange) this.onChange();
    clearTimeout(this._timer);
    this._timer = setTimeout(() => this.flush(), 300);
  }

  flush() {
    clearTimeout(this._timer);
    const copy = JSON.parse(JSON.stringify(this.data));
    if (this._canEncrypt()) {
      for (const [a, b] of SECRET_PATHS) {
        const v = copy.settings[a][b];
        if (v) copy.settings[a][b] = 'enc:' + this.safeStorage.encryptString(v).toString('base64');
      }
    }
    fs.mkdirSync(path.dirname(this.file), { recursive: true });
    const tmp = this.file + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(copy, null, 2), { mode: 0o600 });
    fs.renameSync(tmp, this.file);
  }

  get settings() {
    return this.data.settings;
  }

  setSettings(s) {
    this.data.settings = deepMerge(DEFAULT_SETTINGS, s);
    this.save();
  }

  get company() {
    return this.data.company;
  }

  setCompany(c) {
    this.data.company = { ...this.data.company, ...c };
    this.save();
  }

  get customers() {
    return this.data.customers;
  }

  setCustomers(list) {
    this.data.customers = list;
    this.save();
  }

  // Replace everything with a loaded snapshot. Credentials missing from the
  // snapshot are kept from the current state.
  replaceAll(snapshot, { keepCredentials = false } = {}) {
    const current = this.data.settings;
    const appState = this.data.appState;
    this.data = deepMerge(DEFAULT_DATA, snapshot);
    this.data.appState = appState;
    if (keepCredentials) {
      for (const [a, b] of SECRET_PATHS) this.data.settings[a][b] = current[a][b];
    }
    this.flush();
  }

  appendLog(entry) {
    this.data.log.push(entry);
    if (this.data.log.length > MAX_LOG) this.data.log.splice(0, this.data.log.length - MAX_LOG);
    this.save();
  }

  get parties() {
    return this.data.parties;
  }

  setParties(list) {
    this.data.parties = list;
    this.save();
  }

  resetConversations() {
    this.data.threads = {};
    this.data.msgIndex = {};
    this.data.sentIds = {};
    this.data.processedIds = {};
    this.data.pending = [];
    this.save();
  }
}

module.exports = { Store, DEFAULT_SETTINGS };
