'use strict';

// Regenerates docs/third-party-licenses.md from the production dependency tree
// (exactly what electron-builder packs into the app). Run with: npm run licenses

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const found = new Map();

function resolveDir(name, from) {
  for (let d = from; ; d = path.dirname(d)) {
    const p = path.join(d, 'node_modules', name);
    if (fs.existsSync(path.join(p, 'package.json'))) return p;
    if (d === path.dirname(d)) return null;
  }
}

function walk(name, from) {
  const dir = resolveDir(name, from);
  if (!dir) return;
  const pj = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const key = `${pj.name}@${pj.version}`;
  if (found.has(key)) return;
  const license = typeof pj.license === 'object' ? pj.license.type
    : pj.license || (pj.licenses || []).map((l) => l.type).join(' OR ') || 'UNKNOWN';
  let repo = typeof pj.repository === 'string' ? pj.repository : pj.repository && pj.repository.url;
  if (repo) repo = repo.replace(/^git\+/, '').replace(/\.git$/, '').replace(/^git:\/\//, 'https://').replace(/^github:/, 'https://github.com/');
  if (repo && !/^https?:/.test(repo)) repo = `https://github.com/${repo}`;
  found.set(key, { name: pj.name, version: pj.version, license, repo: repo || pj.homepage || '' });
  for (const dep of Object.keys(pj.dependencies || {})) walk(dep, dir);
}

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
for (const dep of Object.keys(pkg.dependencies)) walk(dep, root);
const electron = JSON.parse(fs.readFileSync(path.join(root, 'node_modules', 'electron', 'package.json'), 'utf8'));

const rows = [...found.values()].sort((a, b) => a.name.localeCompare(b.name));
const counts = {};
for (const r of rows) counts[r.license] = (counts[r.license] || 0) + 1;

const md = `# Third-party licenses

Senario Manager is licensed under the [GNU GPL v3](../LICENSE). Built copies of the app also
contain the open-source components below, each under its own license. All of them are
compatible with GPL-3.0.

This file is generated by \`npm run licenses\` from the production dependency tree. Please
don't edit it by hand.

## Runtime

| Component | Version | License |
|---|---|---|
| [Electron](https://github.com/electron/electron) (includes Chromium and Node.js; see \`LICENSES.chromium.html\` in the installed app) | ${electron.version} | ${electron.license} |

## Packages bundled in the app (${rows.length})

Summary: ${Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([l, n]) => `${l} × ${n}`).join(', ')}.

| Package | Version | License |
|---|---|---|
${rows.map((r) => `| ${r.repo ? `[${r.name}](${r.repo})` : r.name} | ${r.version} | ${r.license} |`).join('\n')}
`;

const out = path.join(root, 'docs', 'third-party-licenses.md');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, md);
console.log(`wrote ${path.relative(root, out)}: ${rows.length} packages`);
const unknown = rows.filter((r) => r.license === 'UNKNOWN');
if (unknown.length) console.warn('No license field:', unknown.map((r) => r.name).join(', '));
